<a href="https://colab.research.google.com/github/shivckr/Python-Projects-/blob/master/1_Exploring_Keras_Tokenizer_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf
print(tf.__version__)

1.15.0


# Build Data

In [0]:
documents = ['Natural language processing (NLP) is a subfield of linguistics, computer science, information engineering, and artificial intelligence concerned with the interactions between computers and human (natural) languages, in particular how to program computers to process and analyze large amounts of natural language data.',
             
            'Challenges in natural language processing frequently involve speech recognition, natural language understanding, and natural language generation.']

# Build Tokenizer

In [0]:

from tensorflow.python.keras.preprocessing.text import Tokenizer

Initialize and fit the text

In [0]:
t = Tokenizer() 

In [0]:
t.fit_on_texts(documents)

Lets look into Tokenizer

In [5]:
t.word_counts  #Each word and how many times they appeared across all docs

OrderedDict([('natural', 6),
             ('language', 5),
             ('processing', 2),
             ('nlp', 1),
             ('is', 1),
             ('a', 1),
             ('subfield', 1),
             ('of', 2),
             ('linguistics', 1),
             ('computer', 1),
             ('science', 1),
             ('information', 1),
             ('engineering', 1),
             ('and', 4),
             ('artificial', 1),
             ('intelligence', 1),
             ('concerned', 1),
             ('with', 1),
             ('the', 1),
             ('interactions', 1),
             ('between', 1),
             ('computers', 2),
             ('human', 1),
             ('languages', 1),
             ('in', 2),
             ('particular', 1),
             ('how', 1),
             ('to', 2),
             ('program', 1),
             ('process', 1),
             ('analyze', 1),
             ('large', 1),
             ('amounts', 1),
             ('data', 1),
             ('challenges'

In [0]:
t.document_count #Number of documents Tokenizer got fit on

2

In [6]:
t.word_index #Unique index of each word in Tokenizer

{'a': 11,
 'amounts': 33,
 'analyze': 31,
 'and': 3,
 'artificial': 18,
 'between': 24,
 'challenges': 35,
 'computer': 14,
 'computers': 6,
 'concerned': 20,
 'data': 34,
 'engineering': 17,
 'frequently': 36,
 'generation': 41,
 'how': 28,
 'human': 25,
 'in': 7,
 'information': 16,
 'intelligence': 19,
 'interactions': 23,
 'involve': 37,
 'is': 10,
 'language': 2,
 'languages': 26,
 'large': 32,
 'linguistics': 13,
 'natural': 1,
 'nlp': 9,
 'of': 5,
 'particular': 27,
 'process': 30,
 'processing': 4,
 'program': 29,
 'recognition': 39,
 'science': 15,
 'speech': 38,
 'subfield': 12,
 'the': 22,
 'to': 8,
 'understanding': 40,
 'with': 21}

In [9]:
t.word_docs #How many documents a word appeared in.

defaultdict(int,
            {'a': 1,
             'amounts': 1,
             'analyze': 1,
             'and': 2,
             'artificial': 1,
             'between': 1,
             'challenges': 1,
             'computer': 1,
             'computers': 1,
             'concerned': 1,
             'data': 1,
             'engineering': 1,
             'frequently': 1,
             'generation': 1,
             'how': 1,
             'human': 1,
             'in': 2,
             'information': 1,
             'intelligence': 1,
             'interactions': 1,
             'involve': 1,
             'is': 1,
             'language': 2,
             'languages': 1,
             'large': 1,
             'linguistics': 1,
             'natural': 2,
             'nlp': 1,
             'of': 1,
             'particular': 1,
             'process': 1,
             'processing': 2,
             'program': 1,
             'recognition': 1,
             'science': 1,
             'speech': 1,


# Converting docs to Matrix

In [10]:
t.texts_to_matrix(documents)

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
t.texts_to_matrix(documents,mode='count')

array([[0., 3., 2., 3., 1., 2., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 3., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
t.texts_to_matrix(documents,mode='tfidf')

array([[0.        , 1.07202493, 0.86490296, 1.07202493, 0.51082562,
        1.17360019, 1.17360019, 0.51082562, 1.17360019, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 1.07202493, 1.07202493, 0.51082562, 0.51082562,
        0.        , 0.        , 0.51082562, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.     